services:
  # A Flask web service
  - type: web
    name: flythrough-ai
    runtime: python
    buildCommand: ./setup_render.sh
    startCommand: gunicorn wsgi:app
    env: python
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1  # 1GB of persistent storage
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FLASK_ENV
        value: "production"
      - key: RENDER
        value: "true"
    autoDeploy: true
